apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applications.postgresql.name }}
  namespace: development
spec:
  project: default
  source:
    repoURL: https://github.com/henesi/StreamRecorder-Helm-Charts/
    targetRevision: master
    path: {{ .Values.applications.postgresql.repoPath }}
  destination:
    server: {{ .Values.applications.cluster.server }}
    namespace: {{ .Values.applications.postgresql.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true